version: "3"

services:
  web:
    image: httpd:latest
    container_name: apache
    volumes:
      - ./magento:/var/www/html
      - ./apache:/usr/local/apache2/conf
    ports:
      - "80:80"
    depends_on:
      - magento

  magento:
    image: markoshust/magento-nginx:latest
    container_name: magento
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - ./magento:/var/www/html
    depends_on:
      - db
      - elasticsearch

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  db_data:
  es_data:
