version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs

  nodejs:
    build:
      context: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
