version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    image: node:14
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    depends_on:
      - db
      - blockchain

  db:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  blockchain:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP

  awscli:
    image: amazon/aws-cli:latest
    volumes:
      - ~/.aws:/root/.aws
    entrypoint: "/bin/sh -c"
    command: "while true; do sleep 1000; done"

volumes:
  dynamodata:
