version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  awscli:
    image: amazon/aws-cli:latest
    volumes:
      - ~/.aws:/root/.aws
    entrypoint: "/bin/sh -c"
    command: "while true; do sleep 1000; done"

volumes:
  pgdata:
