version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask

  flask:
    build: ./flask
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/blogdb
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
    depends_on:
      - postgres

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

