version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - game-server
      - api-server

  game-server:
    image: node:14
    volumes:
      - ./game-server:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    depends_on:
      - db

  api-server:
    image: node:14
    volumes:
      - ./api-server:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
